import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Inter } from 'next/font/google'
import "./globals.css";
import {ClerkProvider, UserButton} from "@clerk/nextjs";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-inter'
})


export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body className={`${geistMono.variable} ${geistMono.variable} antialiased`}>

            <div style={{ position: "fixed", top: 20, right: 20, zIndex: 1000 }}>
                <UserButton />
            </div>

            {children}
            </body>
            </html>
        </ClerkProvider>
    );
}
